namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum ConnectSpanSegmentsAtRouteNodeErrorCodes
    {
        INVALID_ROUTE_NODE_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_SEGMENT_LIST_CANNOT_BE_EMPTY,
        SPAN_SEGMENT_NOT_FOUND,
        SPAN_EQUIPMENT_AND_ROUTE_NODE_WHERE_TO_CONNECT_IS_NOT_COLOCATED,
        SPAN_EQUIPMENT_NOT_AFFIXED_TO_NODE_CONTAINER,
        OUTER_SPAN_IS_NOT_CUT,
        SPAN_SEGMENT_ALREADY_CONNECTED,
        EXPECTED_SPAN_SEGMENTS_FROM_TWO_SPAN_EQUIPMENT,
        EXPECTED_SAME_NUMBER_OF_SPAN_SEGMENTS_BELONGING_TO_TWO_SPAN_EQUIPMENT,
        EXPECTED_SAME_SPECIFICATIONS_OF_SPAN_SEGMENTS_BELONGING_TO_TWO_SPAN_EQUIPMENT,
        SPAN_SEGMENT_END_NOT_FOUND
    }
}
