namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum PlaceSpanEquipmentInUtilityNetworkErrorCodes
    {
        INVALID_SPAN_EQUIPMENT_ID_CANNOT_BE_EMPTY,
        INVALID_SPAN_EQUIPMENT_SPECIFICATION_ID_NOT_FOUND,
        INVALID_INTEREST_KIND_MUST_BE_WALK_OF_INTEREST,
        INVALID_SPAN_EQUIPMENT_ALREADY_EXISTS,
        ROUTING_HOPS_CANNOT_BE_NULL_OR_EMPTY,
        INVALID_SPAN_SEGMENT_ID,
        ERROR_TRACING_SPAN_SEGMENT,
        ERROR_CALCULATING_WALK
    }
}
