namespace OpenFTTH.UtilityGraphService.API.Commands
{
    public enum TerminalEquipmentErrorCodes
    {
        INVALID_TERMINAL_EQUIPMENT_ID_CANNOT_BE_EMPTY,
        INVALID_TERMINAL_EQUIPMENT_ID_ALREAD_EXISTS,
        INVALID_TERMINAL_EQUIPMENT_SPECIFICATION_ID_NOT_FOUND,
        INVALID_NODE_CONTAINER_ID_CANNOT_BE_EMPTY,
        NODE_CONTAINER_NOT_FOUND,
    }
}
